name: Build and Deploy to R-universe

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'  # Runs daily

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and Publish to R-universe
        run: |
          curl -X POST "https://r-universe.dev/update?user=ahmad-alqabandi"
